on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to run your tests"
        type: choice
        required: true
        default: "staging"
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the application
        run: echo "Deploying the application to ${{ inputs.environment }}"